name: Build & Deploy Slides

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to upload release assets
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Chromium dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            fonts-liberation \
            libappindicator3-1 \
            libasound2t64 \
            libatk-bridge2.0-0 \
            libatk1.0-0 \
            libcups2 \
            libdbus-1-3 \
            libgdk-pixbuf2.0-0 \
            libnspr4 \
            libnss3 \
            libx11-xcb1 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            xdg-utils

      - name: Build static site
        run: npm run build

      - name: Export PDF
        run: npm run pdf

      - name: Export PPTX
        run: npx marp slides/index.md --pptx -o site/whitepaper-philosophy.pptx --allow-local-files

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Upload PDF to release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: site/whitepaper-philosophy.pdf
          asset_name: whitepaper-philosophy.pdf
          asset_content_type: application/pdf

      - name: Upload PPTX to release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: site/whitepaper-philosophy.pptx
          asset_name: whitepaper-philosophy.pptx
          asset_content_type: application/vnd.openxmlformats-officedocument.presentationml.presentation
          
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

